# Generated by Django 4.2 on 2023-04-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='password1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
