# Generated by Django 4.2 on 2023-05-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
